# Generated by Django 3.0.4 on 2020-04-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200410_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='lastNews',
            field=models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
