# Generated by Django 3.0.4 on 2020-05-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
