# Generated by Django 3.0.4 on 2020-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200327_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='googleplus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='pinterest',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setting',
            name='youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
